# Configurações gerais
name: Felipe Chama
source: .
destination: ./_site
baseurl: "/projetos/felipechama.com" 
url: "http://www.felipechama.com" 
markdown: kramdown

# Diretórios e arquivos ignorados pelo jekyll
exclude: []

# Paginação
#paginate: 2
#paginate_path: "/:num/"

# Opções do SASS
sass:
  sass_dir:  _sass
  style: :expanded 
  #:compressed

# Configurações do site 
title: Felipe Chama Web Developer 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
