# Configurações gerais
name: Felipe Chama
source: .
destination: ./_site
baseurl: "" 
url: "http://www.felipechama.com" 
markdown: kramdown

# Diretórios e arquivos ignorados pelo jekyll
exclude: []

# Paginação
#paginate: 2
#paginate_path: "/:num/"

# Opções do SASS
sass:
  sass_dir:  _sass
  style: :expanded 
  #:compressed

# Configurações do site 
title: Felipe Chama - Programador Web
description: > # this means to ignore newlines until "baseurl:"
  25 anos, brasileiro, programador web. Formado em Ciência da Computação e apaixonado por tecnologia. 
  HTML5, CSS3, Javascript e Responsive Web Design.
